### PR TITLE
Limit 2gb on 32 bit

### PR DESCRIPTION
**Pull request by Rosuav**
Builds on #46 to try to fix ssize_t issues. There are a couple of things that don't work on Python 3.10, and hopefully this fixes them. Since I don't have a Windows system to test on, I'm depending on CI to tell me if there's a problem.

### CODE REVIEW

**Comment by jd-boyd** [comment]
I'm not sure why they aren't showing. It looks like the AppVeyor config for windows testing stopped working altogether. TravisCI for linux testing ran, but it didn't show the results in this PR.  Here is a link to the results: https://travis-ci.org/github/jd-boyd/python-lzo/builds/768711848

**Comment by Rosuav** [comment]
Hmm. I was hoping to see a Windows build, since that's what I can't do myself, but it WAS building previously, and seemed to have just the one test failure, so hopefully that's all good.

Thanks for merging!

**Comment by jd-boyd** [comment]
Here is the result of the windows build: https://ci.appveyor.com/project/jd-boyd/python-lzo/builds/38926229  
I still will have to look into why they aren't updating correctly on the PRs.

**Comment by jd-boyd** [comment]
Frankly, most of the time, I don't have a windows setup handy for testing and rely on running test PRs through AppVeyor.  I wish I could find an affordable service for MacOS as well.

**Comment by jd-boyd** [comment]
Again, thank you so much for your contribution. It was extremely refreshing.

**Comment by Rosuav** [comment]
Ohh, gotcha, cool, thanks. And yeah, it would be awesome if we could all just push code somewhere and have a bunch of eggs built... the PyPA looks into it periodically but it hasn't gone anywhere yet.

**Comment by Rosuav** [comment]
And, no problem. It scratched an itch :) I keep lots of Python versions around, so it's not THAT big a deal to have to use 3.9 instead of 3.10, but when it's a program that I don't use often, my automatic habit is to type `python3 scriptname.py` and then it was failing :)

**Pull request merged**
