### PR TITLE
Added support for compression and decompression using all algorithms supported by LZO C library 

### LINKED ISSUE #24: Support lzo1y_decompress_safe
Is there any plan to support _lzo1y_decompress_safe_ in decompress method?

### LINKED ISSUE #53: Include support for lzo1z_decompress!
Please include support for decompression (and/or compression) using lzo1z module as well.

### PR DESCRIPTION
**Pull request by pyroclastLapilli**
Added LZO1, LZO1A, LZO1B, LZO1C, LZO1F, LZO1X, LZO1Y, LZO1Z, LZO2A and LZO1X (default) as optional parameters in compress and decompress functions.

resolves #53 , resolves #24. Was not sure if version should be updated to 1.16 or not, set it up as 1.16 in the pr.

Further Improvements and suggestions are solicited.

Thanks.

### CODE REVIEW

**Comment by jd-boyd** [comment]
Thank you very much for this. I will review it later this week.  It would be nice if tests were added for at least a few of the newly support algorithms.

**Comment by pyroclastLapilli** [comment]
Added test cases. Also changed the algorithm argument to keyword argument instead of positional in order to maintain backwards compatibility.

Only minor itch is that LZO1 and LZO1A returns invalid header error for empty input and I did not debug why...just avoided them in the test case.

Cheers

**Comment by jd-boyd** [comment]
> Only minor itch is that LZO1 and LZO1A returns invalid header error for empty input and I did not debug why...just avoided them in the test case.

It would be really nice to see that fixed, but it can be a different pull request I guess.

**Comment by pyroclastLapilli** [comment]
Thanks for merging the pull request. 
When do you plan to publish the new versions on PyPi?

**Comment by jd-boyd** [comment]
> When do you plan to publish the new versions on PyPi?

I was hoping to get #60 finished first. That will hopefully resolve the most common issues people have building it on macOS and Windows. It isn't broken on those platforms, but people have trouble with manually supplying the C library dependency.

**Comment by pyroclastLapilli** [comment]
> I was hoping to get #60 finished first. That will hopefully resolve the most common issues people have building it on macOS and Windows. It isn't broken on those platforms, but people have trouble with manually supplying the C library dependency.

Yeah, that would be great.

**Pull request merged**
